# Generated by Django 4.0.2 on 2022-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='avail_end_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='avail_start_dt',
            field=models.DateField(),
        ),
    ]
