# Generated by Django 4.0.2 on 2022-03-08 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='deleted',
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='VoucherLine',
        ),
    ]
