# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_voucher_voucher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='voucherline',
            old_name='voucher_line_id',
            new_name='id',
        ),
    ]
