# Generated by Django 4.0.2 on 2022-03-17 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_voucher_avail_end_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='avail_end_dt',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31), null=True),
        ),
    ]
