# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wishlist_item_id',
            new_name='id',
        ),
    ]
