# Generated by Django 4.0.2 on 2022-03-14 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItemLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
            ],
            options={
                'db_table': 'image_item_line',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('prod', 'Product'), ('pack', 'Package')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('oos', 'Out of Stock'), ('hidden', 'Hidden'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], max_length=20)),
                ('thumbnail', models.ImageField(upload_to=item.models.upload_to)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(max_length=45, unique=True)),
                ('stock', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ManyToManyField(blank=True, max_length=8, related_name='item', through='item.ImageItemLine', to='image.Image')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('avail_start_tm', models.DateTimeField()),
                ('avail_end_tm', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
            },
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('category', models.CharField(choices=[('rte', 'Ready-To-Eat'), ('rtc', 'Ready-To-Cook'), ('paste', 'Paste')], max_length=30)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holding_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_lead_tm', models.IntegerField(blank=True, null=True)),
                ('max_lead_tm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
            bases=('item.item',),
        ),
        migrations.AddField(
            model_name='imageitemline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_item', to='item.package')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_item', to='item.product')),
            ],
            options={
                'db_table': 'package_item',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ManyToManyField(related_name='package', through='item.PackageItem', to='item.Product'),
        ),
    ]
