# Generated by Django 4.0.2 on 2022-03-01 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageline',
            name='img',
        ),
        migrations.RemoveField(
            model_name='imageline',
            name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('oos', 'Out of Stock'), ('hidden', 'Hidden'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('prod', 'Product'), ('pack', 'Package')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rte', 'Ready-To-Eat'), ('rtc', 'Ready-To-Cook'), ('paste', 'Paste')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageLine',
        ),
    ]
