# Generated by Django 4.0.2 on 2022-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
