# Generated by Django 4.0.2 on 2022-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_img_imageitemline_image_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitemline',
            name='img_line_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
