# Generated by Django 4.0.2 on 2022-03-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_item_id_alter_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pack',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='item',
        ),
    ]
