# Generated by Django 4.0.2 on 2022-03-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_imageitemline_img_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImageItemLine',
        ),
    ]
