# Generated by Django 4.0.2 on 2022-03-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_remove_image_item_delete_imageitemline'),
        ('item', '0004_remove_item_image_delete_imageitemline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItemLine',
            fields=[
                ('img_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
            ],
            options={
                'db_table': 'image_item_line',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='item', through='item.ImageItemLine', to='image.Image'),
        ),
        migrations.AddField(
            model_name='imageitemline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
