# Generated by Django 4.0.2 on 2022-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_image_image'),
        ('item', '0005_imageitemline_item_image_imageitemline_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(blank=True, max_length=8, related_name='item', through='item.ImageItemLine', to='image.Image'),
        ),
    ]
