# Generated by Django 4.0.2 on 2022-03-03 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_product_managers_alter_product_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('prod', 'Product'), ('pack', 'Package')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('oos', 'Out of Stock'), ('hidden', 'Hidden'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], max_length=20)),
                ('thumbnail', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=45, unique=True)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('rte', 'Ready-To-Eat'), ('rtc', 'Ready-To-Cook'), ('paste', 'Paste')], max_length=30)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holding_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_lead_tm', models.IntegerField(blank=True, null=True)),
                ('max_lead_tm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ProductView',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.item'),
        ),
    ]
