# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalitem',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historicalpackageitem',
            old_name='pack_item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='imageitemline',
            old_name='img_line_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='packageitem',
            old_name='pack_item_id',
            new_name='id',
        ),
    ]
