# Generated by Django 4.0.2 on 2022-03-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_productview_alter_item_last_update_alter_item_sku_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='item', serialize=False, to='item.item'),
        ),
    ]
