# Generated by Django 4.0.2 on 2022-03-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('root_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'snapshot',
            },
        ),
        migrations.CreateModel(
            name='SnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=32)),
                ('fk_field', models.CharField(max_length=64, null=True)),
                ('fk_value', models.CharField(max_length=64, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snapshot')),
            ],
            options={
                'db_table': 'snapshot_record',
            },
        ),
    ]
