# Generated by Django 4.0.2 on 2022-03-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotrecord',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='Snapshot',
        ),
        migrations.DeleteModel(
            name='SnapshotRecord',
        ),
    ]
