# Generated by Django 4.0.2 on 2022-03-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
