# Generated by Django 4.0.2 on 2022-03-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustAcc',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cust_acc',
            },
        ),
        migrations.CreateModel(
            name='CustPosDeclarQues',
            fields=[
                ('pos_declar_ques_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'cust_pos_declar_ques',
            },
        ),
        migrations.CreateModel(
            name='CustType',
            fields=[
                ('cust_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cust_type',
            },
        ),
        migrations.CreateModel(
            name='CustProfile',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customer.custacc')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cust_profile',
            },
        ),
        migrations.CreateModel(
            name='CustPosReg',
            fields=[
                ('pos_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_num', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_dt', models.DateTimeField()),
                ('accept', models.IntegerField()),
                ('accepted_by', models.ForeignKey(db_column='accepted_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cust_pos_reg',
            },
        ),
        migrations.CreateModel(
            name='CustPosDeclar',
            fields=[
                ('pos_decl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=300)),
                ('pos_declar_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.custposdeclarques')),
                ('pos_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.custposreg')),
            ],
            options={
                'db_table': 'cust_pos_declar',
            },
        ),
        migrations.AddField(
            model_name='custacc',
            name='cust_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.custtype'),
        ),
        migrations.AddField(
            model_name='custacc',
            name='pos_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.custposreg'),
        ),
    ]
