# Generated by Django 4.0.2 on 2022-03-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custacc',
            name='status',
        ),
    ]
