# Generated by Django 4.0.2 on 2022-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custposreg',
            options={'managed': False},
        ),
    ]
