# Generated by Django 4.0.2 on 2022-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_custposreg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custposreg',
            options={},
        ),
    ]
