# Generated by Django 4.0.2 on 2022-03-22 13:59

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
        ('customer', '0003_alter_custposreg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custposreg',
            name='ic_num',
        ),
        migrations.RemoveField(
            model_name='custposreg',
            name='reg_dt',
        ),
        migrations.AddField(
            model_name='custposreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custposreg',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custposreg',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='custposreg',
            name='postcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custposreg',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custposreg',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('seperated', 'Seperated'), ('divorced', 'Divorced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='custposreg',
            name='occupation',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custposreg',
            name='position',
            field=models.CharField(choices=[('cust', 'Customer'), ('agent', 'Agent'), ('drpshpr', 'Dropshipper')], max_length=30),
        ),
    ]
