# Generated by Django 4.0.2 on 2022-03-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_custposreg_ic_num_remove_custposreg_reg_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custposreg',
            name='accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custposreg',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.custtype'),
        ),
    ]
