# Generated by Django 4.0.2 on 2022-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_custposreg_accept_alter_custposreg_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custposreg',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
