# Generated by Django 4.0.2 on 2022-03-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Credit / Debit Card'), ('fpx', 'Online Banking')], max_length=20),
        ),
    ]
