# Generated by Django 4.0.2 on 2022-03-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='PickupLoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pickup_loc',
            },
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=45)),
                ('weight_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_end', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.courier')),
            ],
            options={
                'db_table': 'shipping_fee',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.ordershipment')),
                ('created_tms', models.DateTimeField()),
                ('track_num', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.shippingaddress')),
                ('ship_fee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.shippingfee')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.ordershipment')),
                ('pickup_dt', models.DateTimeField()),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.pickuploc')),
            ],
            options={
                'db_table': 'pickup',
            },
        ),
    ]
