# Generated by Django 4.0.2 on 2022-04-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postcode', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('shipping', 'shipping')], max_length=20)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'order_shipment',
            },
        ),
        migrations.CreateModel(
            name='PickupLoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pickup_loc',
            },
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_start', models.IntegerField()),
                ('weight_end', models.IntegerField()),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_weight', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.state')),
            ],
            options={
                'db_table': 'shipping_fee',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ordershipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment')),
                ('track_num', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.postcode')),
            ],
            options={
                'db_table': 'shipment',
            },
            bases=('shipment.ordershipment',),
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('ordershipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('pickup_dt', models.DateTimeField(blank=True, null=True)),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.pickuploc')),
            ],
            options={
                'db_table': 'pickup',
            },
            bases=('shipment.ordershipment',),
        ),
    ]
