# Generated by Django 4.0.2 on 2022-03-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'order_shipment',
            },
        ),
        migrations.CreateModel(
            name='PickupLoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pickup_loc',
            },
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=45)),
                ('weight_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_end', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.courier')),
            ],
            options={
                'db_table': 'shipping_fee',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ordershipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment')),
                ('track_num', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.shippingaddress')),
                ('ship_fee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.shippingfee')),
            ],
            options={
                'db_table': 'shipment',
            },
            bases=('shipment.ordershipment',),
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('ordershipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment')),
                ('pickup_dt', models.DateTimeField()),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.pickuploc')),
            ],
            options={
                'db_table': 'pickup',
            },
            bases=('shipment.ordershipment',),
        ),
    ]
