# Generated by Django 4.0.2 on 2022-03-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.state'),
        ),
    ]
