# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='courier_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pickuploc',
            old_name='pickup_loc_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingfee',
            old_name='ship_fee_id',
            new_name='id',
        ),
    ]
