# Generated by Django 4.0.2 on 2022-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuploc',
            name='location',
            field=models.CharField(max_length=80),
        ),
    ]
