# Generated by Django 4.0.2 on 2022-03-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_shippingfee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_end',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_start',
            field=models.IntegerField(max_length=8),
        ),
    ]
