# Generated by Django 4.0.2 on 2022-04-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_pickuploc_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='sub_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_end',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_start',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
