# Generated by Django 4.0.2 on 2022-03-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_alter_shippingfee_weight_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='weight_start',
            field=models.IntegerField(),
        ),
    ]
