# Generated by Django 4.0.2 on 2022-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_alter_shippingfee_weight_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingfee',
            name='sub_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
