# Generated by Django 4.0.2 on 2022-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_shippingfee_sub_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='sub_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
