# Generated by Django 4.0.2 on 2022-03-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0001_initial'),
        ('shipment', '0007_shippingfee_sub_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'order_shipment',
            },
        ),
        migrations.CreateModel(
            name='PickupLoc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pickup_loc',
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='ordershipment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('ordershipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipment.ordershipment')),
                ('pickup_dt', models.DateTimeField()),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.pickuploc')),
            ],
            options={
                'db_table': 'pickup',
            },
            bases=('shipment.ordershipment',),
        ),
    ]
