# Generated by Django 4.0.2 on 2022-03-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_ordershipment_pickuploc_remove_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ship_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
