# Generated by Django 4.0.2 on 2022-03-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
        ('shipment', '0009_alter_shipment_ship_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='contact_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='contact_num',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='postcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.postcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
