# Generated by Django 4.0.2 on 2022-03-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_shipment_contact_name_shipment_contact_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='order',
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('shipping', 'shipping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='track_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
