# Generated by Django 4.0.2 on 2022-03-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0011_remove_ordershipment_order_alter_ordershipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ship_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipment.shippingfee'),
        ),
    ]
