# Generated by Django 4.0.2 on 2022-03-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_alter_shipment_ship_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ship_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
