# Generated by Django 4.0.2 on 2022-03-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_alter_shipment_ship_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickup_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
