# Generated by Django 4.0.2 on 2022-02-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
    ]
