# Generated by Django 4.0.2 on 2022-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_admin_first_name_admin_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
    ]
