const breadcrumbNameMap: any = {
  '/dashboard': 'Dashboard',
  '/product': 'Product',
  '/product/inventory': 'Product Inventory',
  '/product/add': 'Add Product',
  '/package': 'Package',
  '/package/inventory': 'Package Inventory',
  '/package/add': 'Add Package',
  '/order': 'Order',
  '/order/add': 'Add Order',
  '/shipment': 'Shipment',
  '/shipment/shipping-fee': 'Shipping Fee Management',
  '/customer': 'Customer',
  '/customer/registrations': 'Agent/Dropshipper Registration',
  '/customer/add': 'Add Customer',
  '/business-insights': 'Business Insights',
  '/business-insights/inventory-analysis': 'Inventory Analysis',
  '/voucher': 'Voucher',
  '/voucher/add': 'Add Voucher',
  '/my-acc': 'My Account',
  '/my-acc/acc-settings': 'Account Settings',
  '/admin': 'Admin',
  '/admin/add': 'Add Admin',
  '/help': 'Help',
};

export default breadcrumbNameMap;
