const breadcrumbNameMap = {
  '/dashboard': 'Dashboard',
  '/product/management': 'Product Management',
  '/product/inventory': 'Product Inventory',
  '/product/add': 'Add Product',
  '/package/management': 'Package Management',
  '/package/inventory': 'Package Inventory',
  '/order/management': 'Order Management',
  '/order/pending': 'Pending Orders',
  '/order/add': 'Add Order',
  '/shipment/management': 'Shipment Management',
  '/shipment/shipping-fee': 'Shipping Fee Management',
  '/customer/management': 'Customer Management',
  '/customer/registrations': 'Agent/Dropshipper Registration Management',
  '/customer/add': 'Add Customer',
  '/business-insights/statistics': 'Statistics',
  '/business-insights/inventory-analysis': 'Inventory Analysis',
  '/discount/management': 'Discount Management',
  '/discount/add': 'Add Discount',
  '/my-acc/profile-management': 'Profile Management',
  '/my-acc/acc-settings': 'Account Settings',
  '/admin/management': 'Admin Management',
  '/admin/add': 'Add Admin',
  '/help': 'Help',
}

export default breadcrumbNameMap
