const breadcrumbNameMap: any = {
  '/dashboard': 'Dashboard',
  '/product': 'Product',
  '/product/inventory': 'Product Inventory',
  '/product/add': 'Add Product',
  '/product/:id': 'Edit Product',
  '/package': 'Package',
  '/package/inventory': 'Package Inventory',
  '/package/add': 'Add Package',
  '/package/:id': 'Edit Package',
  '/order': 'Order',
  '/order/add': 'Add Order',
  '/shipment': 'Shipment',
  '/shipment/shipping_fee': 'Shipping Fee Management',
  '/customer': 'Customer',
  '/customer/registration': 'Agent/Dropshipper Registration',
  '/customer/add': 'Add Customer',
  '/customer/:id': 'Edit Customer',
  '/business_insights': 'Business Insights',
  '/business_insights/inventory_analysis': 'Inventory Analysis',
  '/voucher': 'Voucher',
  '/voucher/add': 'Add Voucher',
  '/voucher/:id': 'Edit Voucher',
  '/my_acc': 'My Account',
  '/my_acc/acc_settings': 'Account Settings',
  '/admin': 'Admin',
  '/admin/add': 'Add Admin',
  '/help': 'Help',
};

export default breadcrumbNameMap;
