# Generated by Django 4.0.2 on 2022-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
