# Generated by Django 4.0.2 on 2022-03-16 15:45

from django.db import migrations, models
import image.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=image.models.upload_to)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
