# Generated by Django 4.0.2 on 2022-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
