# Generated by Django 4.0.2 on 2022-03-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_imageitemline_image_item_imageitemline_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.DeleteModel(
            name='ImageItemLine',
        ),
    ]
