# Generated by Django 4.0.2 on 2022-03-13 06:30

from django.db import migrations
import image.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_remove_image_item_delete_imageitemline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=image.models.upload_to),
        ),
    ]
