# Generated by Django 4.0.2 on 2022-03-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_rename_img_id_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='image_id',
        ),
    ]
