# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_rename_id_image_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='id',
        ),
    ]
