# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='postcode',
            old_name='postal_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_id',
            new_name='id',
        ),
    ]
