# Generated by Django 4.0.2 on 2022-02-21 18:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_num', models.CharField(max_length=15)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'admin',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_tms', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='CustAcc',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cust_acc',
            },
        ),
        migrations.CreateModel(
            name='CustPosDeclarQues',
            fields=[
                ('pos_declar_ques_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'cust_pos_declar_ques',
            },
        ),
        migrations.CreateModel(
            name='CustType',
            fields=[
                ('cust_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cust_type',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_tms', models.DateTimeField()),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.custacc')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('order_ship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.order')),
            ],
            options={
                'db_table': 'order_shipment',
            },
        ),
        migrations.CreateModel(
            name='PickupLoc',
            fields=[
                ('pickup_loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pickup_loc',
            },
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('postal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.city')),
            ],
            options={
                'db_table': 'postcode',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt', models.IntegerField()),
                ('usage_limit', models.IntegerField()),
                ('avail_start_tm', models.DateTimeField()),
                ('avail_end_tm', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_tms', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.custacc')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='CustProfile',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administrator.custacc')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cust_profile',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.item')),
                ('avail_start_tm', models.DateTimeField()),
                ('avail_end_tm', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.item')),
                ('category', models.CharField(max_length=30)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordering_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holding_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_lead_tm', models.IntegerField(blank=True, null=True)),
                ('max_lead_tm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('wishlist_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.wishlist')),
            ],
            options={
                'db_table': 'wishlist_item',
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('voucher_line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.custtype')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.voucher')),
            ],
            options={
                'db_table': 'voucher_line',
            },
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('ship_fee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=45)),
                ('weight_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_end', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ship_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.courier')),
            ],
            options={
                'db_table': 'shipping_fee',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('default', models.IntegerField(blank=True, null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.custacc')),
                ('postal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.postcode')),
            ],
            options={
                'db_table': 'shipping_address',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_tms', models.DateTimeField(blank=True, null=True)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.custacc')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.item')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.IntegerField()),
                ('reference_num', models.CharField(max_length=50)),
                ('created_tms', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.order')),
            ],
            options={
                'db_table': 'order_line',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.voucher'),
        ),
        migrations.CreateModel(
            name='ImageLine',
            fields=[
                ('img_line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
            ],
            options={
                'db_table': 'image_line',
            },
        ),
        migrations.CreateModel(
            name='CustPosReg',
            fields=[
                ('pos_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_num', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_dt', models.DateTimeField()),
                ('accept', models.IntegerField()),
                ('accepted_by', models.ForeignKey(db_column='accepted_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('postal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.postcode')),
            ],
            options={
                'db_table': 'cust_pos_reg',
            },
        ),
        migrations.CreateModel(
            name='CustPosDeclar',
            fields=[
                ('pos_decl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=300)),
                ('pos_declar_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.custposdeclarques')),
                ('pos_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.custposreg')),
            ],
            options={
                'db_table': 'cust_pos_declar',
            },
        ),
        migrations.AddField(
            model_name='custacc',
            name='cust_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.custtype'),
        ),
        migrations.AddField(
            model_name='custacc',
            name='pos_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.custposreg'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.state'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.item')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.custacc'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.ordershipment')),
                ('created_tms', models.DateTimeField()),
                ('track_num', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.shippingaddress')),
                ('ship_fee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.shippingfee')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrator.ordershipment')),
                ('pickup_dt', models.DateTimeField()),
                ('pickup_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.pickuploc')),
            ],
            options={
                'db_table': 'pickup',
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('pack_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.package')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.product')),
            ],
            options={
                'db_table': 'package_item',
            },
        ),
    ]
