# Generated by Django 4.0.2 on 2022-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_num',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
