# Generated by Django 4.0.2 on 2022-04-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('default', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
