# Generated by Django 4.0.2 on 2022-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('default', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_address',
            },
        ),
    ]
