# Generated by Django 4.0.2 on 2022-02-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postcode', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('default', models.IntegerField(blank=True, null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.custacc')),
                ('postal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.postcode')),
            ],
            options={
                'db_table': 'shipping_address',
            },
        ),
    ]
