# Generated by Django 4.0.2 on 2022-03-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postcode.postcode'),
        ),
        migrations.DeleteModel(
            name='Postcode',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
