# Generated by Django 4.0.2 on 2022-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
