# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_shippingaddress_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_id',
            new_name='id',
        ),
    ]
