# Generated by Django 4.0.2 on 2022-03-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcode', '0001_initial'),
        ('customer', '0001_initial'),
        ('shipment', '0001_initial'),
        ('address', '0003_alter_shippingaddress_postal_delete_postcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Address',
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
