# Generated by Django 4.0.2 on 2022-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_rename_shippingaddress_address_alter_address_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
