# Generated by Django 4.0.2 on 2022-03-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal',
            new_name='postcode',
        ),
    ]
