# Generated by Django 4.0.2 on 2022-03-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_cart_id_alter_cartitem_cart_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item_id',
            new_name='id',
        ),
    ]
