# Generated by Django 4.0.2 on 2022-03-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('cart', '0003_alter_cart_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cust'),
        ),
    ]
