# Generated by Django 4.0.2 on 2022-03-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('shipping', 'shipping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('cancel', 'Cancellation'), ('unpaid', 'Unpaid'), ('toShip', 'To Ship'), ('shipping', 'Shipping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
