# Generated by Django 4.0.2 on 2022-03-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0011_remove_ordershipment_order_alter_ordershipment_type_and_more'),
        ('order', '0003_alter_order_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_type',
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='shipment.ordershipment'),
            preserve_default=False,
        ),
    ]
