# Generated by Django 4.0.2 on 2022-03-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('order', '0004_remove_order_ship_type_order_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='weight',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='item.item'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='order.order'),
        ),
    ]
