# Generated by Django 4.0.2 on 2022-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderline_price_orderline_special_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
