# Generated by Django 4.0.2 on 2022-03-29 05:21

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderline_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=order.models.create_unique_id, max_length=40, primary_key=True, serialize=False),
        ),
    ]
