# Generated by Django 4.0.2 on 2022-04-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0011_remove_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='customer.cust'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('cancel', 'Cancellation'), ('unpaid', 'Unpaid'), ('toShip', 'To Ship'), ('toPick', 'To Pickup'), ('shipping', 'Shipping')], max_length=20),
        ),
    ]
